"""اصناف — تاکسونومیِ ثابتِ «این کسب‌وکار چه می‌فروشد».

**چرا جدا از `industry`.** ستونِ `Tenant.industry` هم «صنف» نامیده می‌شود ولی کارِ
دیگری می‌کند: پنج گزینه‌ی درشت که **قالبِ ماژول‌های پنل** را انتخاب می‌کنند
(`app/services/modules.py`). این‌جا لایه‌ی ریزتری است — «بستنی‌فروشی»، «لوازم یدکی
خودرو» — که با آن دو کسب‌وکار به هم **وصل** می‌شوند: شرکتِ پخش اعلام می‌کند به کدام
اصناف جنس می‌دهد، و فروشگاه در بازار همان‌ها را می‌بیند.

**چرا ثابت در کد و نه جدولِ per-tenant.** این یک برچسبِ محلی نیست، **کلیدِ تطبیق
بینِ دو مستأجر** است. اگر هر کسب‌وکار صنفِ خودش را می‌نوشت، «لوازم یدکی» و «یدکی
فروشی» دو چیزِ متفاوت می‌شدند و هدف‌گیریِ پخش‌کننده بی‌صدا از کار می‌افتاد. همان
دلیلی که `INDUSTRY_TEMPLATES` هم در کد است.

**گروه‌ها رفتار ندارند.** فقط برای سازمان‌دهی‌اند: `<optgroup>` در انتخابگر، و
دکمه‌ی «کلِ این گروه» وقتی پخش‌کننده هدف‌هایش را می‌چیند. به `industry` نگاشت
نمی‌شوند — ثبت‌نام آن را جدا می‌پرسد.

**افزودنِ صنفِ تازه** = یک ردیف این‌جا. کلیدها هرگز عوض نمی‌شوند، چون در
`tenants.trade`، `marketplace_settings.target_trades` و
`marketplace_listings.extra_trades` ذخیره شده‌اند؛ برچسبِ فارسی آزاد است.

**چرا فهرست این‌قدر بلند است.** این «فهرستِ همه‌ی مشاغلِ دنیا» نیست — چنین چیزی
انتها ندارد. هدفش این است که تقریباً هر فروشگاه، کارگاه، شرکتِ پخش و مرکزِ خدماتیِ
بازارِ ایران خودش را این‌جا پیدا کند و مجبور نشود «سایر» بزند. هرچه بیشتر `other`
انتخاب شود، هدف‌گیریِ پخش‌کننده بی‌اثرتر می‌شود.

**سه چیز آزاد است، یکی نیست.** جابه‌جا کردنِ یک صنف بینِ گروه‌ها، عوض‌کردنِ برچسبِ
فارسی، و افزودنِ ردیفِ تازه — هر سه بی‌خطرند (کلیدِ گروه هیچ‌جا ذخیره نمی‌شود).
آنچه آزاد **نیست**، برداشتنِ یک کلیدِ منتشرشده است: صنفِ اعلام‌شده‌ی یک کسب‌وکارِ
واقعی به رشته‌ی ناشناخته تبدیل می‌شود، `trade_label` خودِ کلید را برمی‌گرداند و
`distributor_matches_trade` با هیچ هدفی جور نمی‌شود — بی‌آنکه خطایی بدهد.
`test_legacy_keys_survive_every_taxonomy_change` نگهبانِ همین است.
"""
from typing import NamedTuple


class Trade(NamedTuple):
    """یک صنف. `key` در دیتابیس می‌نشیند، `label` فقط دیده می‌شود."""

    key: str
    label: str


class TradeGroup(NamedTuple):
    key: str
    label: str
    trades: tuple[Trade, ...]


#: حداکثر طولِ کلید — با `String(40)`ِ `tenants.trade` یکی است. تست نگهش می‌دارد.
MAX_TRADE_KEY_LEN = 40


TRADE_GROUPS: tuple[TradeGroup, ...] = (
    TradeGroup(
        "food",
        "مواد غذایی، خواربار و محصولات مصرفی",
        (
            Trade("supermarket", "سوپرمارکت"),
            Trade("hypermarket", "هایپرمارکت"),
            Trade("grocery", "بقالی"),
            Trade("food_chain_store", "فروشگاه زنجیره‌ای مواد غذایی"),
            Trade("food_store", "فروشگاه مواد غذایی"),
            Trade("food_wholesale", "بنکداری مواد غذایی"),
            Trade("rice_store", "برنج‌فروشی"),
            Trade("legumes_store", "حبوبات‌فروشی"),
            Trade("spice_store", "ادویه‌فروشی"),
            Trade("tea_store", "چای‌فروشی"),
            Trade("coffee_store", "قهوه‌فروشی"),
            Trade("saffron_store", "زعفران‌فروشی"),
            Trade("dates_store", "خرمافروشی"),
            Trade("honey_store", "عسل‌فروشی"),
            Trade("nuts", "آجیل و خشکبار"),
            Trade("produce", "میوه و تره‌بار"),
            Trade("fruit_store", "میوه‌فروشی"),
            Trade("vegetable_store", "سبزی‌فروشی"),
            Trade("organic_food", "محصولات ارگانیک"),
            Trade("diet_food", "محصولات رژیمی"),
            Trade("healthy_food", "محصولات سلامت‌محور"),
            Trade("local_food", "فروش محصولات محلی"),
            Trade("rural_products", "فروش محصولات روستایی"),
            Trade("dairy", "لبنیاتی"),
            Trade("traditional_dairy", "فروش لبنیات سنتی"),
            Trade("butcher", "قصابی"),
            Trade("red_meat", "گوشت قرمز"),
            Trade("poultry_fish", "مرغ و ماهی"),
            Trade("poultry_store", "مرغ‌فروشی"),
            Trade("seafood_store", "ماهی و آبزیان"),
            Trade("protein_store", "پروتئینی"),
            Trade("egg_poultry_store", "تخم‌مرغ و محصولات طیور"),
            Trade("frozen_food", "مواد غذایی منجمد"),
            Trade("packaged_food", "کنسرو و مواد بسته‌بندی"),
            Trade("imported_food", "مواد غذایی خارجی"),
            Trade("gluten_free_food", "محصولات بدون گلوتن"),
        ),
    ),
    TradeGroup(
        "bakery_sweets",
        "نان، شیرینی، دسر و نوشیدنی",
        (
            Trade("bakery", "نانوایی"),
            Trade("traditional_bakery", "نان سنتی"),
            Trade("fantasy_bakery", "نان فانتزی"),
            Trade("industrial_bakery", "نان صنعتی"),
            Trade("confectionery", "قنادی و شیرینی"),
            Trade("traditional_sweets", "شیرینی سنتی"),
            Trade("cake_dessert", "کیک و دسر"),
            Trade("custom_cake", "کیک سفارشی"),
            Trade("chocolate_store", "شکلات‌فروشی"),
            Trade("icecream", "بستنی‌فروشی"),
            Trade("juice_icecream", "آبمیوه و بستنی"),
            Trade("beverages", "نوشیدنی و آبمیوه"),
            Trade("beverage_store", "فروش آب معدنی و نوشیدنی"),
        ),
    ),
    TradeGroup(
        "restaurant_catering",
        "رستوران و تهیه غذا",
        (
            Trade("restaurant", "رستوران"),
            Trade("traditional_restaurant", "رستوران سنتی"),
            Trade("iranian_restaurant", "رستوران ایرانی"),
            Trade("international_restaurant", "رستوران بین‌المللی"),
            Trade("fastfood", "فست‌فود"),
            Trade("pizza_store", "پیتزافروشی"),
            Trade("sandwich_shop", "ساندویچی"),
            Trade("burger_shop", "همبرگرفروشی"),
            Trade("fried_chicken", "سوخاری"),
            Trade("kebab_shop", "کبابی"),
            Trade("liver_kebab_shop", "جگرکی"),
            Trade("ash_halim", "آش و حلیم"),
            Trade("traditional_offal_restaurant", "طباخی"),
            Trade("takeaway_food", "غذای بیرون‌بر"),
            Trade("catering_food", "تهیه غذا"),
            Trade("catering", "کترینگ"),
            Trade("corporate_catering", "غذای شرکتی"),
            Trade("event_catering", "غذای مجالس"),
            Trade("cafe", "کافه"),
            Trade("coffee_shop", "کافی‌شاپ"),
            Trade("cafe_restaurant", "کافه‌رستوران"),
            Trade("tea_house", "چایخانه"),
            Trade("breakfast_shop", "صبحانه‌سرا"),
        ),
    ),
    TradeGroup(
        "apparel",
        "پوشاک",
        (
            Trade("clothing", "پوشاک"),
            Trade("boutique", "بوتیک"),
            Trade("mens_clothing", "پوشاک مردانه"),
            Trade("womens_clothing", "پوشاک زنانه"),
            Trade("childrens_wear", "پوشاک بچگانه"),
            Trade("baby_clothing", "پوشاک نوزاد"),
            Trade("manto_store", "مانتو"),
            Trade("scarf_store", "شال و روسری"),
            Trade("formal_wear", "لباس مجلسی"),
            Trade("suit_store", "کت و شلوار"),
            Trade("sportswear", "پوشاک اسپرت"),
            Trade("casual_homewear", "لباس راحتی"),
            Trade("underwear", "لباس زیر"),
            Trade("socks_store", "جوراب"),
            Trade("sleepwear", "لباس خواب"),
            Trade("athletic_clothing", "لباس ورزشی"),
            Trade("workwear", "لباس کار و ایمنی"),
            Trade("uniform_store", "لباس فرم"),
            Trade("plus_size_clothing", "پوشاک سایز بزرگ"),
            Trade("traditional_clothing", "پوشاک محلی و سنتی"),
            Trade("bridal_wear", "لباس عروس"),
            Trade("fashion_maison", "مزون"),
            Trade("mens_tailoring", "خیاطی مردانه"),
            Trade("womens_tailoring", "خیاطی زنانه"),
            Trade("clothing_manufacturer", "تولیدی پوشاک"),
        ),
    ),
    TradeGroup(
        "footwear_leather",
        "کیف، کفش و چرم",
        (
            Trade("shoes_bags", "کیف و کفش"),
            Trade("mens_shoes", "کفش مردانه"),
            Trade("womens_shoes", "کفش زنانه"),
            Trade("childrens_shoes", "کفش بچگانه"),
            Trade("sports_shoes", "کفش ورزشی"),
            Trade("safety_shoes", "کفش ایمنی"),
            Trade("bag_store", "کیف"),
            Trade("school_bag", "کیف مدرسه"),
            Trade("luggage", "چمدان"),
            Trade("leather_goods", "محصولات چرمی"),
            Trade("leather_bags", "کیف چرمی"),
            Trade("leather_shoes", "کفش چرمی"),
            Trade("leather_accessories", "کمربند و اکسسوری چرمی"),
            Trade("shoe_bag_repair", "تعمیر کیف و کفش"),
        ),
    ),
    TradeGroup(
        "fabric_haberdashery",
        "پارچه و خرازی",
        (
            Trade("fabric", "پارچه‌فروشی"),
            Trade("upholstery_fabric", "پارچه مبلی"),
            Trade("curtain_fabric", "پارچه پرده‌ای"),
            Trade("haberdashery", "خرازی"),
            Trade("yarn_knitting", "کاموا و بافتنی"),
            Trade("sewing_supplies", "لوازم خیاطی"),
            Trade("garment_accessories", "دکمه و یراق پوشاک"),
            Trade("sewing_machine", "چرخ خیاطی"),
        ),
    ),
    TradeGroup(
        "cosmetics_care",
        "آرایشی، بهداشتی و عطر",
        (
            Trade("cosmetics", "لوازم آرایشی و بهداشتی"),
            Trade("makeup_store", "لوازم آرایشی"),
            Trade("skincare", "محصولات پوست"),
            Trade("haircare", "محصولات مو"),
            Trade("personal_hygiene", "محصولات بهداشت شخصی"),
            Trade("perfume", "عطر و ادکلن"),
            Trade("perfume_making", "عطرسازی"),
            Trade("salon_equipment", "تجهیزات آرایشگاهی"),
            Trade("nail_products", "محصولات ناخن"),
            Trade("shaving_products", "محصولات اصلاح"),
        ),
    ),
    TradeGroup(
        "beauty_services",
        "سالن و خدمات زیبایی",
        (
            Trade("barber", "آرایشگاه و پیرایش"),
            Trade("mens_barber", "آرایشگاه مردانه"),
            Trade("beauty_salon", "سالن زیبایی"),
            Trade("nail_salon", "خدمات ناخن"),
            Trade("skin_care_salon", "خدمات پوست"),
            Trade("hair_salon", "خدمات مو"),
            Trade("hair_coloring", "رنگ و مش"),
            Trade("epilation", "اپیلاسیون"),
            Trade("eyebrow_services", "خدمات ابرو"),
            Trade("makeup_artist", "میکاپ"),
            Trade("makeup_studio", "گریم"),
            Trade("massage_center", "مرکز ماساژ مجاز"),
        ),
    ),
    TradeGroup(
        "health_medical",
        "سلامت و تجهیزات پزشکی",
        (
            Trade("pharmacy", "داروخانه"),
            Trade("medical_equipment", "تجهیزات پزشکی"),
            Trade("hospital_equipment", "تجهیزات بیمارستانی"),
            Trade("medical_supplies", "لوازم پزشکی مصرفی"),
            Trade("laboratory_equipment", "لوازم آزمایشگاهی"),
            Trade("dental_equipment", "تجهیزات دندانپزشکی"),
            Trade("orthopedic_store", "محصولات ارتوپدی"),
            Trade("optician", "عینک‌فروشی"),
            Trade("medical_glasses", "عینک طبی"),
            Trade("sunglasses", "عینک آفتابی"),
            Trade("hearing_aid", "سمعک"),
            Trade("rehabilitation_equipment", "تجهیزات توانبخشی"),
            Trade("elderly_equipment", "تجهیزات سالمندان"),
            Trade("herbal", "عطاری و گیاهان دارویی"),
            Trade("supplement", "مکمل و تغذیه‌ی ورزشی"),
        ),
    ),
    TradeGroup(
        "medical_services",
        "خدمات درمانی",
        (
            Trade("medical_office", "مطب پزشکی"),
            Trade("clinic", "درمانگاه"),
            Trade("dentistry", "دندانپزشکی"),
            Trade("medical_lab", "آزمایشگاه"),
            Trade("medical_imaging", "تصویربرداری پزشکی"),
            Trade("physiotherapy", "فیزیوتراپی"),
            Trade("occupational_therapy", "کاردرمانی"),
            Trade("speech_therapy", "گفتاردرمانی"),
            Trade("rehabilitation_center", "مرکز توانبخشی"),
            Trade("nursing_services", "مرکز پرستاری"),
            Trade("home_care", "خدمات مراقبت در منزل"),
            Trade("counseling_center", "مرکز مشاوره"),
        ),
    ),
    TradeGroup(
        "mobile_telecom",
        "موبایل و ارتباطات",
        (
            Trade("mobile", "موبایل و لوازم جانبی"),
            Trade("mobile_store", "موبایل‌فروشی"),
            Trade("mobile_accessories", "لوازم جانبی موبایل"),
            Trade("mobile_repair", "تعمیر موبایل"),
            Trade("mobile_parts", "قطعات موبایل"),
            Trade("sim_card_store", "فروش سیم‌کارت"),
            Trade("telecom_services", "خدمات اپراتور"),
            Trade("telephone_store", "تلفن ثابت و بی‌سیم"),
            Trade("telecom_equipment", "تجهیزات مخابراتی"),
            Trade("telecom_network_equipment", "تجهیزات شبکه مخابراتی"),
        ),
    ),
    TradeGroup(
        "computer_it",
        "کامپیوتر و فناوری اطلاعات",
        (
            Trade("computer", "کامپیوتر و قطعات"),
            Trade("laptop_store", "لپ‌تاپ"),
            Trade("computer_parts", "قطعات کامپیوتر"),
            Trade("computer_accessories", "لوازم جانبی کامپیوتر"),
            Trade("monitor_store", "مانیتور"),
            Trade("printer_scanner", "پرینتر و اسکنر"),
            Trade("printer_consumables", "مواد مصرفی پرینتر"),
            Trade("computer_repair", "تعمیر کامپیوتر"),
            Trade("laptop_repair", "تعمیر لپ‌تاپ"),
            Trade("network_equipment", "تجهیزات شبکه"),
            Trade("server_datacenter", "سرور و دیتاسنتر"),
            Trade("storage_devices", "ذخیره‌سازی و هارد"),
            Trade("it_services", "خدمات کامپیوتری و نرم‌افزار"),
            Trade("software_company", "شرکت نرم‌افزاری"),
            Trade("web_design", "طراحی سایت"),
            Trade("network_services", "خدمات شبکه"),
            Trade("it_support", "پشتیبانی IT"),
            Trade("cybersecurity_services", "امنیت سایبری"),
            Trade("cloud_services", "خدمات ابری"),
            Trade("software_sales", "فروش نرم‌افزار"),
        ),
    ),
    TradeGroup(
        "av_camera",
        "دوربین، صوت و تصویر",
        (
            Trade("audio_video", "صوتی و تصویری"),
            Trade("television_store", "تلویزیون"),
            Trade("audio_system", "سیستم صوتی"),
            Trade("home_theater", "سینمای خانگی"),
            Trade("camera", "دوربین و تجهیزات تصویربرداری"),
            Trade("photography_camera", "دوربین عکاسی"),
            Trade("video_camera", "دوربین فیلمبرداری"),
            Trade("photography_equipment", "لوازم عکاسی"),
            Trade("studio_equipment", "تجهیزات استودیو"),
            Trade("cctv", "دوربین مداربسته"),
            Trade("cctv_installation", "نصب دوربین مداربسته"),
        ),
    ),
    TradeGroup(
        "gaming_entertainment",
        "بازی و سرگرمی دیجیتال",
        (
            Trade("gaming", "بازی و کنسول"),
            Trade("game_console", "کنسول بازی"),
            Trade("gaming_accessories", "لوازم گیمینگ"),
            Trade("gaming_pc", "کامپیوتر گیمینگ"),
            Trade("video_games", "بازی فیزیکی"),
            Trade("console_repair", "تعمیر کنسول"),
            Trade("game_net", "گیم‌نت"),
        ),
    ),
    TradeGroup(
        "home_appliances",
        "لوازم خانگی",
        (
            Trade("home_appliance", "لوازم خانگی"),
            Trade("major_appliances", "لوازم خانگی بزرگ"),
            Trade("small_appliances", "لوازم خانگی کوچک"),
            Trade("refrigerator_freezer", "یخچال و فریزر"),
            Trade("washing_machine", "ماشین لباسشویی"),
            Trade("dishwasher", "ماشین ظرفشویی"),
            Trade("cooker_store", "اجاق گاز"),
            Trade("microwave_store", "مایکروویو"),
            Trade("vacuum_store", "جاروبرقی"),
            Trade("air_conditioner", "کولر"),
            Trade("heater_store", "بخاری"),
            Trade("water_heater", "آبگرمکن"),
            Trade("water_purifier", "تصفیه آب"),
            Trade("appliance_parts", "قطعات لوازم خانگی"),
            Trade("appliance_repair", "تعمیر لوازم خانگی"),
        ),
    ),
    TradeGroup(
        "housewares",
        "ظروف و لوازم خانه",
        (
            Trade("kitchenware", "ظروف و لوازم آشپزخانه"),
            Trade("porcelain_store", "ظروف چینی"),
            Trade("crystal_glassware", "بلور و کریستال"),
            Trade("steel_kitchenware", "ظروف استیل"),
            Trade("plastic_housewares", "ظروف پلاستیکی"),
            Trade("cookware", "لوازم پخت و پز"),
            Trade("serving_ware", "لوازم پذیرایی"),
            Trade("home_cleaning_supplies", "لوازم نظافت منزل"),
            Trade("dowry_store", "جهیزیه"),
        ),
    ),
    TradeGroup(
        "furniture_decor",
        "مبلمان و دکوراسیون",
        (
            Trade("furniture", "مبلمان و دکوراسیون"),
            Trade("home_furniture", "مبلمان منزل"),
            Trade("office_furniture", "مبلمان اداری"),
            Trade("table_chair", "میز و صندلی"),
            Trade("bedding", "سرویس خواب"),
            Trade("mattress", "تشک"),
            Trade("bed_linen", "کالای خواب"),
            Trade("carpet", "فرش و موکت"),
            Trade("handmade_carpet", "فرش دستباف"),
            Trade("machine_carpet", "فرش ماشینی"),
            Trade("moquette", "موکت"),
            Trade("curtain", "پرده و تزئینات"),
            Trade("wallpaper", "کاغذ دیواری"),
            Trade("interior_decoration", "دکوراسیون داخلی"),
            Trade("mirror_console", "آینه و کنسول"),
            Trade("decorative_art", "تابلو دکوراتیو"),
            Trade("flowers", "گل و گیاه"),
            Trade("flower_shop", "گل‌فروشی"),
            Trade("indoor_plants", "گیاهان آپارتمانی"),
        ),
    ),
    TradeGroup(
        "lighting_electrical",
        "روشنایی و برق ساختمان",
        (
            Trade("lighting", "لوستر و روشنایی"),
            Trade("lamp_lighting", "لامپ و روشنایی"),
            Trade("led_equipment", "تجهیزات LED"),
            Trade("electrical", "لوازم برقی و الکتریکی"),
            Trade("switch_socket", "کلید و پریز"),
            Trade("wire_cable", "سیم و کابل"),
            Trade("electrical_panel", "تابلو برق"),
            Trade("industrial_electrical", "تجهیزات برق صنعتی"),
            Trade("building_electrician", "برق‌کاری ساختمان"),
        ),
    ),
    TradeGroup(
        "building_materials",
        "ساختمان و مصالح",
        (
            Trade("building_material", "مصالح ساختمانی"),
            Trade("cement_store", "سیمان"),
            Trade("gypsum_store", "گچ"),
            Trade("brick_store", "آجر"),
            Trade("block_store", "بلوک"),
            Trade("sand_gravel", "شن و ماسه"),
            Trade("concrete", "بتن"),
            Trade("building_stone", "سنگ ساختمانی"),
            Trade("stone_cutting", "سنگبری"),
            Trade("tile", "کاشی و سرامیک"),
            Trade("mosaic_store", "موزاییک"),
            Trade("wood_mdf", "چوب و MDF"),
            Trade("wood_products", "تخته و مصنوعات چوبی"),
            Trade("false_ceiling", "سقف کاذب"),
            Trade("drywall", "کناف"),
            Trade("building_insulation", "عایق ساختمانی"),
            Trade("waterproofing", "ایزوگام"),
            Trade("scaffolding", "داربست"),
        ),
    ),
    TradeGroup(
        "plumbing_hvac",
        "لوله، تأسیسات و تهویه",
        (
            Trade("plumbing", "لوازم بهداشتی ساختمان"),
            Trade("faucets", "شیرآلات"),
            Trade("sanitary_ware", "چینی بهداشتی"),
            Trade("pipes_fittings", "لوله و اتصالات"),
            Trade("water_pump", "پمپ آب"),
            Trade("water_tank", "مخزن آب"),
            Trade("hvac", "تأسیسات و تهویه"),
            Trade("heating_system", "سیستم گرمایشی"),
            Trade("cooling_system", "سیستم سرمایشی"),
            Trade("boiler_room_services", "موتورخانه"),
            Trade("air_conditioning", "تهویه مطبوع"),
            Trade("plumbing_services", "لوله‌کشی"),
        ),
    ),
    TradeGroup(
        "doors_glass",
        "درب، پنجره و شیشه",
        (
            Trade("doors_windows", "درب و پنجره"),
            Trade("upvc_windows", "پنجره UPVC"),
            Trade("security_door", "درب ضدسرقت"),
            Trade("automatic_door", "درب اتوماتیک"),
            Trade("glass_mirror", "شیشه و آینه"),
            Trade("building_glass", "شیشه ساختمانی"),
            Trade("tempered_glass", "شیشه سکوریت"),
            Trade("electric_shutter", "کرکره برقی"),
        ),
    ),
    TradeGroup(
        "cabinet_wood",
        "کابینت و صنایع چوب",
        (
            Trade("cabinet", "کابینت"),
            Trade("kitchen_cabinet", "کابینت آشپزخانه"),
            Trade("carpentry", "نجاری"),
            Trade("woodcraft", "مصنوعات چوبی"),
            Trade("wooden_door", "درب چوبی"),
            Trade("wall_wardrobe", "کمد دیواری"),
            Trade("wood_cnc", "CNC چوب"),
        ),
    ),
    TradeGroup(
        "tools_hardware",
        "ابزار و یراق",
        (
            Trade("tools", "ابزارفروشی"),
            Trade("hand_tools", "ابزار دستی"),
            Trade("power_tools", "ابزار برقی"),
            Trade("industrial_tools", "ابزار صنعتی"),
            Trade("measurement_tools", "ابزار اندازه‌گیری"),
            Trade("hardware", "یراق‌آلات"),
            Trade("fasteners", "پیچ و مهره"),
            Trade("locks_hardware", "قفل و یراق"),
            Trade("industrial_adhesive", "چسب صنعتی"),
            Trade("welding_equipment", "تجهیزات جوشکاری"),
        ),
    ),
    TradeGroup(
        "metal_industry",
        "آهن، فلز و صنایع فلزی",
        (
            Trade("iron_metal", "آهن‌آلات و فلزات"),
            Trade("iron_store", "آهن‌فروشی"),
            Trade("steel_store", "فولاد"),
            Trade("metal_sheet", "ورق فلزی"),
            Trade("metal_profile", "پروفیل"),
            Trade("metal_pipe", "لوله فلزی"),
            Trade("aluminum_store", "آلومینیوم"),
            Trade("copper_store", "مس"),
            Trade("stainless_steel", "استیل"),
            Trade("metal_scrap", "ضایعات فلزی"),
            Trade("blacksmith", "آهنگری"),
            Trade("welding_services", "جوشکاری"),
            Trade("machining", "تراشکاری"),
            Trade("milling_services", "فرزکاری"),
            Trade("metal_cnc", "CNC فلز"),
            Trade("foundry", "ریخته‌گری"),
        ),
    ),
    TradeGroup(
        "paint_chemicals",
        "رنگ، رزین و شیمیایی",
        (
            Trade("paint", "رنگ و رزین"),
            Trade("building_paint", "رنگ ساختمانی"),
            Trade("industrial_paint", "رنگ صنعتی"),
            Trade("solvents", "تینر و حلال"),
            Trade("adhesive_store", "چسب"),
            Trade("resin_store", "رزین"),
            Trade("industrial_chemicals", "مواد شیمیایی صنعتی"),
            Trade("chemical_raw_material", "مواد اولیه شیمیایی"),
        ),
    ),
    TradeGroup(
        "automotive",
        "خودرو",
        (
            Trade("car_dealership", "نمایشگاه خودرو"),
            Trade("new_car_sales", "خودرو صفر"),
            Trade("used_car_sales", "خودرو کارکرده"),
            Trade("autoparts", "لوازم یدکی خودرو"),
            Trade("car_body_parts", "قطعات بدنه خودرو"),
            Trade("engine_parts", "قطعات موتور"),
            Trade("suspension_parts", "قطعات جلوبندی"),
            Trade("auto_electrical_parts", "قطعات برقی خودرو"),
            Trade("tires", "لاستیک و رینگ"),
            Trade("tire_store", "لاستیک"),
            Trade("wheel_rim", "رینگ"),
            Trade("car_battery", "باتری خودرو"),
            Trade("oil_filter", "روغن و فیلتر"),
            Trade("motor_oil", "روغن موتور"),
            Trade("car_filters", "فیلتر خودرو"),
            Trade("car_accessories", "صوتی و تزئینات خودرو"),
            Trade("car_audio", "سیستم صوتی خودرو"),
            Trade("car_alarm", "دزدگیر خودرو"),
            Trade("car_interior_accessories", "روکش و کفپوش خودرو"),
            Trade("car_sport_accessories", "لوازم اسپرت خودرو"),
        ),
    ),
    TradeGroup(
        "auto_services",
        "خدمات خودرو",
        (
            Trade("auto_repair", "تعمیرگاه خودرو"),
            Trade("auto_mechanic", "مکانیکی"),
            Trade("auto_electrician", "برق خودرو"),
            Trade("battery_service", "باتری‌سازی"),
            Trade("injector_service", "انژکتورشویی"),
            Trade("car_diagnostics", "دیاگ خودرو"),
            Trade("suspension_service", "جلوبندی‌سازی"),
            Trade("wheel_alignment", "میزان فرمان"),
            Trade("oil_change", "تعویض روغن"),
            Trade("tire_repair", "آپاراتی"),
            Trade("auto_body_repair", "صافکاری"),
            Trade("auto_painting", "نقاشی خودرو"),
            Trade("paintless_dent_repair", "صافکاری بدون رنگ"),
            Trade("auto_glass", "شیشه خودرو"),
            Trade("exhaust_service", "اگزوزسازی"),
            Trade("radiator_service", "رادیاتورسازی"),
            Trade("transmission_service", "گیربکس خودرو"),
            Trade("engine_repair", "تعمیر موتور"),
            Trade("car_ac_service", "کولر خودرو"),
            Trade("car_wash", "کارواش"),
            Trade("car_detailing", "دیتیلینگ خودرو"),
            Trade("car_ceramic_coating", "سرامیک خودرو"),
            Trade("car_inspection", "کارشناسی خودرو"),
            Trade("roadside_assistance", "امداد خودرو"),
            Trade("tow_service", "یدک‌کش"),
        ),
    ),
    TradeGroup(
        "motorcycle_bicycle",
        "موتورسیکلت و دوچرخه",
        (
            Trade("motorcycle_dealer", "فروش موتورسیکلت"),
            Trade("motorcycle_parts", "لوازم یدکی موتورسیکلت"),
            Trade("motorcycle_repair", "تعمیر موتورسیکلت"),
            Trade("motorcycle_accessories", "لوازم جانبی موتورسیکلت"),
            Trade("bicycle_store", "دوچرخه"),
            Trade("bicycle_accessories", "لوازم دوچرخه"),
            Trade("bicycle_repair", "تعمیر دوچرخه"),
            Trade("electric_bicycle", "دوچرخه برقی"),
            Trade("electric_scooter", "اسکوتر برقی"),
        ),
    ),
    TradeGroup(
        "industrial_machinery",
        "ماشین‌آلات و تجهیزات صنعتی",
        (
            Trade("industrial_equipment", "تجهیزات صنعتی"),
            Trade("industrial_machinery", "ماشین‌آلات صنعتی"),
            Trade("manufacturing_machinery", "ماشین‌آلات تولید"),
            Trade("compressor", "کمپرسور"),
            Trade("industrial_pump", "پمپ صنعتی"),
            Trade("electric_motor", "موتور الکتریکی"),
            Trade("industrial_gearbox", "گیربکس صنعتی"),
            Trade("bearing_store", "بلبرینگ"),
            Trade("industrial_belts", "تسمه صنعتی"),
            Trade("hydraulic_equipment", "تجهیزات هیدرولیک"),
            Trade("pneumatic_equipment", "تجهیزات پنوماتیک"),
            Trade("industrial_automation", "تجهیزات اتوماسیون"),
            Trade("plc_control", "PLC و کنترل صنعتی"),
            Trade("instrumentation", "ابزار دقیق"),
            Trade("industrial_lab_equipment", "تجهیزات آزمایشگاهی صنعتی"),
            Trade("packaging_machinery", "ماشین‌آلات بسته‌بندی"),
        ),
    ),
    TradeGroup(
        "safety_fire",
        "ایمنی و آتش‌نشانی",
        (
            Trade("safety_equipment", "تجهیزات ایمنی"),
            Trade("ppe", "تجهیزات حفاظت فردی"),
            Trade("work_clothing", "لباس کار"),
            Trade("safety_helmet", "کلاه ایمنی"),
            Trade("fire_equipment", "تجهیزات آتش‌نشانی"),
            Trade("fire_extinguisher", "کپسول آتش‌نشانی"),
            Trade("fire_alarm_system", "سیستم اعلام حریق"),
            Trade("fire_suppression", "سیستم اطفای حریق"),
        ),
    ),
    TradeGroup(
        "stationery_office",
        "لوازم‌التحریر و اداری",
        (
            Trade("stationery", "لوازم‌التحریر"),
            Trade("school_supplies", "لوازم مدرسه"),
            Trade("office_supplies", "لوازم اداری"),
            Trade("office_equipment", "ماشین‌های اداری"),
            Trade("copier_store", "دستگاه کپی"),
            Trade("office_printer", "پرینتر اداری"),
            Trade("pos_equipment", "صندوق فروشگاهی"),
            Trade("barcode_equipment", "بارکدخوان"),
            Trade("attendance_device", "دستگاه حضور و غیاب"),
        ),
    ),
    TradeGroup(
        "books_culture",
        "کتاب، آموزش و فرهنگ",
        (
            Trade("bookstore", "کتاب‌فروشی"),
            Trade("academic_books", "کتاب دانشگاهی"),
            Trade("childrens_books", "کتاب کودک"),
            Trade("educational_books", "کتاب کمک‌آموزشی"),
            Trade("cultural_products", "محصولات فرهنگی"),
            Trade("religious_products", "محصولات مذهبی"),
            Trade("publishing", "انتشارات"),
            Trade("publisher", "ناشر"),
        ),
    ),
    TradeGroup(
        "education_services",
        "آموزش",
        (
            Trade("education", "آموزشگاه"),
            Trade("language_school", "آموزشگاه زبان"),
            Trade("computer_training", "آموزشگاه کامپیوتر"),
            Trade("accounting_training", "آموزشگاه حسابداری"),
            Trade("vocational_training", "آموزشگاه فنی و حرفه‌ای"),
            Trade("music_school", "آموزشگاه موسیقی"),
            Trade("art_school", "آموزشگاه هنری"),
            Trade("driving_school", "آموزشگاه رانندگی"),
            Trade("exam_preparation", "آموزشگاه کنکور"),
            Trade("private_tutoring", "تدریس خصوصی"),
            Trade("kindergarten", "مهدکودک"),
            Trade("preschool", "پیش‌دبستانی"),
            Trade("private_school", "مدرسه غیردولتی"),
            Trade("educational_institute", "موسسه آموزشی"),
            Trade("online_education", "آموزش آنلاین"),
        ),
    ),
    TradeGroup(
        "toys_kids",
        "اسباب‌بازی و کودک",
        (
            Trade("toys", "اسباب‌بازی"),
            Trade("educational_toys", "اسباب‌بازی فکری"),
            Trade("baby_products", "سیسمونی"),
            Trade("baby_transport", "کالسکه و صندلی کودک"),
            Trade("baby_supplies", "لوازم نوزاد"),
            Trade("kids_party_supplies", "لوازم جشن کودک"),
        ),
    ),
    TradeGroup(
        "sports_fitness",
        "ورزش",
        (
            Trade("sports", "لوازم ورزشی"),
            Trade("fitness_equipment", "تجهیزات بدنسازی"),
            Trade("football_equipment", "لوازم فوتبال"),
            Trade("martial_arts_equipment", "لوازم رزمی"),
            Trade("mountaineering", "لوازم کوهنوردی"),
            Trade("camping_equipment", "لوازم کمپینگ"),
            Trade("swimming_equipment", "لوازم شنا"),
            Trade("outdoor_equipment", "لوازم شکار و طبیعت‌گردی مجاز"),
            Trade("gym", "باشگاه ورزشی"),
            Trade("fitness_club", "باشگاه بدنسازی"),
            Trade("sports_complex", "مجموعه ورزشی"),
            Trade("swimming_pool", "استخر"),
            Trade("sports_school", "مدرسه ورزشی"),
        ),
    ),
    TradeGroup(
        "music_art",
        "موسیقی و هنر",
        (
            Trade("music_instruments", "آلات موسیقی"),
            Trade("music_audio_equipment", "تجهیزات صوتی موسیقی"),
            Trade("art_supplies", "لوازم نقاشی"),
            Trade("art_gallery", "گالری هنری"),
            Trade("art_sales", "فروش آثار هنری"),
            Trade("frame_shop", "قاب‌سازی"),
            Trade("handicraft", "صنایع دستی"),
            Trade("pottery", "سفال و سرامیک هنری"),
            Trade("wood_handicraft", "محصولات چوبی هنری"),
            Trade("handmade_leather", "محصولات چرمی دست‌ساز"),
        ),
    ),
    TradeGroup(
        "gifts_events",
        "هدیه و مناسبت",
        (
            Trade("gift_shop", "هدایا و کادویی"),
            Trade("party_supplies", "لوازم تولد"),
            Trade("balloon_decoration", "بادکنک‌آرایی"),
            Trade("candle_store", "شمع"),
            Trade("greeting_cards", "کارت تبریک"),
            Trade("gift_wrapping", "بسته‌بندی هدیه"),
            Trade("promotional_gifts", "گیفت تبلیغاتی"),
        ),
    ),
    TradeGroup(
        "luxury",
        "طلا، جواهر و لوکس",
        (
            Trade("gold", "طلا و جواهر"),
            Trade("gold_store", "طلافروشی"),
            Trade("jewelry_store", "جواهرفروشی"),
            Trade("silver", "نقره‌فروشی"),
            Trade("fashion_jewelry", "بدلیجات"),
            Trade("gemstone", "سنگ‌های قیمتی"),
            Trade("coin_store", "سکه"),
            Trade("watch", "ساعت"),
            Trade("luxury_watch", "ساعت لوکس"),
            Trade("watch_repair", "تعمیر ساعت"),
            Trade("luxury_accessories", "اکسسوری لوکس"),
            Trade("antique", "آنتیک و کلکسیون"),
            Trade("collectibles", "کلکسیون"),
        ),
    ),
    TradeGroup(
        "printing_advertising",
        "چاپ و تبلیغات",
        (
            Trade("printing", "چاپ و تبلیغات"),
            Trade("digital_printing", "چاپ دیجیتال"),
            Trade("offset_printing", "چاپ افست"),
            Trade("banner_printing", "چاپ بنر"),
            Trade("business_card_printing", "چاپ کارت ویزیت"),
            Trade("label_printing", "چاپ لیبل"),
            Trade("garment_printing", "چاپ روی لباس"),
            Trade("object_printing", "چاپ روی اجسام"),
            Trade("stamp_making", "مهرسازی"),
            Trade("sign_making", "تابلوسازی"),
            Trade("outdoor_advertising", "تبلیغات محیطی"),
            Trade("advertising_agency", "کانون تبلیغاتی"),
            Trade("graphic_design", "طراحی گرافیک"),
            Trade("branding_services", "خدمات برندینگ"),
        ),
    ),
    TradeGroup(
        "packaging_industry",
        "بسته‌بندی",
        (
            Trade("packaging", "بسته‌بندی"),
            Trade("carton_manufacturing", "کارتن‌سازی"),
            Trade("box_manufacturing", "جعبه‌سازی"),
            Trade("disposable_products", "ظروف یکبار مصرف"),
            Trade("packaging_containers", "ظروف بسته‌بندی"),
            Trade("plastic_bags", "نایلون و نایلکس"),
            Trade("cellophane", "سلفون"),
            Trade("labels", "لیبل"),
            Trade("printing_packaging", "چاپ و بسته‌بندی"),
        ),
    ),
    TradeGroup(
        "manufacturing",
        "تولیدی و کارگاهی",
        (
            Trade("general_manufacturer", "تولیدی عمومی"),
            Trade("factory", "کارخانه"),
            Trade("workshop", "کارگاه تولیدی"),
            Trade("food_manufacturing", "تولید مواد غذایی"),
            Trade("beverage_manufacturing", "تولید نوشیدنی"),
            Trade("garment_manufacturing", "تولید پوشاک"),
            Trade("shoe_manufacturing", "تولید کفش"),
            Trade("bag_manufacturing", "تولید کیف"),
            Trade("leather_manufacturing", "تولید محصولات چرمی"),
            Trade("plastic_manufacturing", "تولید پلاستیک"),
            Trade("container_manufacturing", "تولید ظروف"),
            Trade("auto_parts_manufacturing", "تولید قطعات خودرو"),
            Trade("industrial_parts_manufacturing", "تولید قطعات صنعتی"),
            Trade("electrical_manufacturing", "تولید تجهیزات برقی"),
            Trade("appliance_manufacturing", "تولید لوازم خانگی"),
            Trade("furniture_manufacturing", "تولید مبلمان"),
            Trade("wood_manufacturing", "تولید مصنوعات چوبی"),
            Trade("metal_manufacturing", "تولید فلزات"),
            Trade("chemical_manufacturing", "تولید مواد شیمیایی"),
            Trade("detergent_manufacturing", "تولید شوینده"),
            Trade("cosmetics_manufacturing", "تولید آرایشی بهداشتی"),
            Trade("pharmaceutical_manufacturing", "تولید دارویی"),
            Trade("assembly_workshop", "مونتاژ"),
        ),
    ),
    TradeGroup(
        "detergent_cellulose",
        "شوینده و سلولزی",
        (
            Trade("detergent_store", "شوینده"),
            Trade("cellulose_products", "محصولات سلولزی"),
            Trade("tissue_products", "دستمال کاغذی"),
            Trade("baby_diapers", "پوشک کودک"),
            Trade("feminine_hygiene", "محصولات بهداشت بانوان"),
            Trade("cleaning_chemicals", "مواد نظافتی"),
            Trade("facility_hygiene", "محصولات بهداشت ساختمان"),
        ),
    ),
    TradeGroup(
        "pets_veterinary",
        "پت و حیوانات",
        (
            Trade("pet_shop", "پت‌شاپ و لوازم حیوانات"),
            Trade("pet_food", "غذای حیوانات"),
            Trade("pet_accessories", "لوازم حیوانات خانگی"),
            Trade("pet_grooming", "آرایش حیوانات"),
            Trade("pet_boarding", "پانسیون حیوانات"),
            Trade("veterinary", "دامپزشکی و لوازم"),
            Trade("veterinary_clinic", "کلینیک دامپزشکی"),
            Trade("veterinary_supplies", "دارو و تجهیزات دامپزشکی"),
        ),
    ),
    TradeGroup(
        "agriculture",
        "کشاورزی",
        (
            Trade("farm_inputs", "نهاده‌های کشاورزی"),
            Trade("seed_store", "بذر"),
            Trade("fertilizer", "کود"),
            Trade("agricultural_pesticides", "سموم کشاورزی مجاز"),
            Trade("growing_medium", "خاک و بستر کشت"),
            Trade("agriculture_tools", "ابزار کشاورزی"),
            Trade("agriculture_equipment", "ادوات کشاورزی"),
            Trade("agriculture_machinery", "ماشین‌آلات کشاورزی"),
            Trade("tractor_parts", "تراکتور و قطعات"),
            Trade("irrigation_equipment", "سیستم آبیاری"),
            Trade("irrigation_pipe", "لوله آبیاری"),
            Trade("greenhouse_equipment", "تجهیزات گلخانه"),
            Trade("greenhouse", "گلخانه و نهال"),
            Trade("nursery_plants", "نهالستان"),
            Trade("gardening_services", "باغبانی"),
        ),
    ),
    TradeGroup(
        "livestock",
        "دام، طیور و آبزیان",
        (
            Trade("animal_feed", "خوراک دام و طیور"),
            Trade("livestock_farm", "دامداری"),
            Trade("poultry_farm", "مرغداری"),
            Trade("fish_farm", "پرورش ماهی"),
            Trade("aquaculture", "شیلات"),
            Trade("beekeeping", "زنبورداری"),
            Trade("livestock_equipment", "تجهیزات دامداری"),
            Trade("poultry_equipment", "تجهیزات مرغداری"),
            Trade("animal_supplement", "مکمل دام و طیور"),
        ),
    ),
    TradeGroup(
        "distribution",
        "پخش و توزیع",
        (
            Trade("distribution_company", "شرکت پخش"),
            Trade("food_distribution", "پخش مواد غذایی"),
            Trade("beverage_distribution", "پخش نوشیدنی"),
            Trade("dairy_distribution", "پخش لبنیات"),
            Trade("protein_distribution", "پخش پروتئین"),
            Trade("nuts_distribution", "پخش خشکبار"),
            Trade("detergent_distribution", "پخش شوینده"),
            Trade("hygiene_distribution", "پخش بهداشتی و شوینده"),
            Trade("cosmetics_distribution", "پخش آرایشی"),
            Trade("cellulose_distribution", "پخش سلولزی"),
            Trade("pharma_distribution", "پخش دارو و مکمل"),
            Trade("medical_distribution", "پخش تجهیزات پزشکی"),
            Trade("clothing_distribution", "پخش پوشاک"),
            Trade("fashion_distribution", "پخش کیف و کفش"),
            Trade("appliance_distribution", "پخش لوازم خانگی"),
            Trade("mobile_distribution", "پخش موبایل"),
            Trade("computer_distribution", "پخش کامپیوتر"),
            Trade("autoparts_distribution", "پخش لوازم یدکی"),
            Trade("oil_distribution", "پخش روغن و فیلتر"),
            Trade("tire_distribution", "پخش لاستیک"),
            Trade("tools_distribution", "پخش ابزار"),
            Trade("electrical_distribution", "پخش لوازم برقی"),
            Trade("building_material_distribution", "پخش مصالح ساختمانی"),
            Trade("industrial_distribution", "پخش لوازم صنعتی"),
            Trade("stationery_distribution", "پخش لوازم‌التحریر"),
            Trade("toy_distribution", "پخش اسباب‌بازی"),
            Trade("agriculture_distribution", "پخش محصولات کشاورزی"),
        ),
    ),
    TradeGroup(
        "wholesale",
        "عمده‌فروشی و بنکداری",
        (
            Trade("general_wholesale", "بنکداری و عمده‌فروشی"),
            Trade("food_wholesaler", "عمده‌فروشی مواد غذایی"),
            Trade("clothing_wholesaler", "عمده‌فروشی پوشاک"),
            Trade("fashion_wholesaler", "عمده‌فروشی کیف و کفش"),
            Trade("cosmetics_wholesaler", "عمده‌فروشی آرایشی"),
            Trade("mobile_wholesaler", "عمده‌فروشی موبایل"),
            Trade("appliance_wholesaler", "عمده‌فروشی لوازم خانگی"),
            Trade("autoparts_wholesaler", "عمده‌فروشی لوازم یدکی"),
            Trade("tools_wholesaler", "عمده‌فروشی ابزار"),
            Trade("industrial_wholesaler", "عمده‌فروشی تجهیزات صنعتی"),
            Trade("agriculture_wholesaler", "عمده‌فروشی محصولات کشاورزی"),
        ),
    ),
    TradeGroup(
        "transport_delivery",
        "حمل‌ونقل",
        (
            Trade("transport", "حمل و نقل"),
            Trade("freight_transport", "حمل بار"),
            Trade("freight_company", "باربری"),
            Trade("local_delivery", "حمل بار شهری"),
            Trade("intercity_freight", "حمل بار بین‌شهری"),
            Trade("heavy_transport", "حمل بار سنگین"),
            Trade("food_transport", "حمل مواد غذایی"),
            Trade("refrigerated_transport", "حمل یخچالی"),
            Trade("moving_company", "حمل اثاثیه"),
            Trade("pickup_delivery", "وانت‌بار"),
            Trade("courier", "پیک"),
            Trade("motorcycle_courier", "پیک موتوری"),
            Trade("taxi_service", "تاکسی سرویس"),
            Trade("employee_transport", "سرویس کارکنان"),
            Trade("school_transport", "سرویس مدرسه"),
        ),
    ),
    TradeGroup(
        "logistics_warehousing",
        "انبار و لجستیک",
        (
            Trade("logistics", "لجستیک"),
            Trade("warehousing", "انبارداری"),
            Trade("public_warehouse", "انبار عمومی"),
            Trade("cold_storage", "سردخانه"),
            Trade("distribution_center", "مرکز توزیع"),
            Trade("fulfillment", "خدمات بسته‌بندی و ارسال"),
            Trade("order_fulfillment", "خدمات ارسال سفارش"),
            Trade("supply_chain_services", "مدیریت زنجیره تأمین"),
            Trade("freight_forwarding", "فورواردر"),
        ),
    ),
    TradeGroup(
        "construction_contracting",
        "ساختمان و پیمانکاری",
        (
            Trade("construction", "پیمانکاری ساختمان"),
            Trade("construction_company", "شرکت ساختمانی"),
            Trade("general_contractor", "پیمانکار عمومی"),
            Trade("civil_contractor", "پیمانکار عمرانی"),
            Trade("mechanical_contractor", "پیمانکار تأسیسات"),
            Trade("electrical_contractor", "پیمانکار برق"),
            Trade("industrial_contractor", "پیمانکار صنعتی"),
            Trade("building_renovation", "بازسازی ساختمان"),
            Trade("renovation_services", "نوسازی"),
            Trade("demolition", "تخریب ساختمان"),
            Trade("excavation", "گودبرداری"),
            Trade("earthmoving", "خاکبرداری"),
            Trade("landscaping", "محوطه‌سازی"),
            Trade("asphalt_services", "آسفالت"),
            Trade("facade_contractor", "اجرای نما"),
            Trade("building_painting", "نقاشی ساختمان"),
            Trade("plastering", "گچ‌کاری"),
            Trade("tiling_services", "کاشی‌کاری"),
            Trade("flooring_services", "کف‌سازی"),
        ),
    ),
    TradeGroup(
        "architecture_engineering",
        "معماری و مهندسی",
        (
            Trade("architecture", "دفتر معماری"),
            Trade("interior_design", "طراحی داخلی"),
            Trade("engineering_office", "دفتر مهندسی"),
            Trade("civil_engineering", "مهندسی عمران"),
            Trade("electrical_engineering", "مهندسی برق"),
            Trade("mechanical_engineering", "مهندسی مکانیک"),
            Trade("surveying", "نقشه‌برداری"),
            Trade("construction_lab", "آزمایشگاه ساختمان"),
            Trade("project_management", "مدیریت پروژه"),
            Trade("engineering_consulting", "مشاوره مهندسی"),
        ),
    ),
    TradeGroup(
        "real_estate_services",
        "املاک",
        (
            Trade("real_estate", "مشاور املاک"),
            Trade("residential_real_estate", "املاک مسکونی"),
            Trade("commercial_real_estate", "املاک تجاری"),
            Trade("industrial_real_estate", "املاک صنعتی"),
            Trade("agricultural_real_estate", "املاک کشاورزی"),
            Trade("property_rental", "اجاره ملک"),
            Trade("property_management", "مدیریت ساختمان"),
            Trade("building_management", "مدیریت مجتمع"),
            Trade("property_appraisal", "خدمات کارشناسی ملک"),
        ),
    ),
    TradeGroup(
        "accounting_finance",
        "حسابداری و مالی",
        (
            Trade("accounting_services", "خدمات حسابداری و مالی"),
            Trade("accounting_office", "دفتر حسابداری"),
            Trade("tax_services", "خدمات مالیاتی"),
            Trade("financial_consulting", "مشاوره مالی"),
            Trade("auditing", "حسابرسی"),
            Trade("payroll_services", "خدمات حقوق و دستمزد"),
            Trade("corporate_finance_services", "خدمات مالی شرکتی"),
            Trade("business_valuation", "ارزش‌گذاری کسب‌وکار"),
        ),
    ),
    TradeGroup(
        "insurance_services",
        "بیمه",
        (
            Trade("insurance", "بیمه"),
            Trade("insurance_agency", "نمایندگی بیمه"),
            Trade("insurance_brokerage", "کارگزاری بیمه"),
            Trade("auto_insurance_services", "خدمات بیمه خودرو"),
            Trade("health_insurance_services", "بیمه درمان"),
            Trade("liability_insurance_services", "بیمه مسئولیت"),
            Trade("business_insurance_services", "بیمه کسب‌وکار"),
        ),
    ),
    TradeGroup(
        "legal_admin",
        "حقوقی و اداری",
        (
            Trade("law_office", "دفتر وکالت"),
            Trade("legal_consulting", "مشاوره حقوقی"),
            Trade("registration_services", "خدمات ثبتی"),
            Trade("company_registration", "ثبت شرکت"),
            Trade("trademark_registration", "ثبت برند"),
            Trade("contract_services", "خدمات قرارداد"),
            Trade("official_translation", "ترجمه رسمی"),
            Trade("translation_office", "دارالترجمه"),
            Trade("administrative_services", "خدمات اداری"),
            Trade("typing_copying", "تایپ و تکثیر"),
        ),
    ),
    TradeGroup(
        "travel_tourism",
        "گردشگری و سفر",
        (
            Trade("travel", "آژانس مسافرتی"),
            Trade("tour_operator", "تور گردشگری"),
            Trade("ticketing", "فروش بلیت"),
            Trade("visa_services", "خدمات ویزا"),
            Trade("domestic_tourism", "گردشگری داخلی"),
            Trade("international_tourism", "گردشگری خارجی"),
            Trade("eco_tourism", "گردشگری طبیعت"),
            Trade("tour_guide", "راهنمای گردشگری"),
            Trade("car_rental", "اجاره خودرو"),
        ),
    ),
    TradeGroup(
        "hospitality",
        "هتل و اقامت",
        (
            Trade("hotel", "هتل"),
            Trade("apartment_hotel", "هتل‌آپارتمان"),
            Trade("guesthouse", "مهمانپذیر"),
            Trade("eco_lodge", "اقامتگاه بومگردی"),
            Trade("inn", "مسافرخانه"),
            Trade("vacation_rental", "ویلا و اقامتگاه"),
            Trade("tourist_camp", "کمپ گردشگری"),
            Trade("private_dormitory", "خوابگاه خصوصی"),
        ),
    ),
    TradeGroup(
        "events_ceremonies",
        "مراسم و تشریفات",
        (
            Trade("banquet_hall", "تالار پذیرایی"),
            Trade("garden_hall", "باغ تالار"),
            Trade("event_services", "تشریفات مراسم"),
            Trade("wedding_services", "خدمات عروسی"),
            Trade("wedding_table_services", "سفره عقد"),
            Trade("floral_design", "گل‌آرایی"),
            Trade("event_decoration", "دکور مراسم"),
            Trade("event_equipment_rental", "اجاره میز و صندلی"),
            Trade("dish_rental", "اجاره ظروف"),
            Trade("event_audio", "تجهیزات صوتی مراسم"),
            Trade("event_music_services", "دی‌جی و خدمات موسیقی مجاز"),
        ),
    ),
    TradeGroup(
        "photography_media",
        "عکاسی و تولید محتوا",
        (
            Trade("photography_studio", "آتلیه عکاسی"),
            Trade("industrial_photography", "عکاسی صنعتی"),
            Trade("commercial_photography", "عکاسی تبلیغاتی"),
            Trade("event_photography", "عکاسی مراسم"),
            Trade("videography", "فیلمبرداری"),
            Trade("content_studio", "استودیو تولید محتوا"),
            Trade("video_editing", "تدوین ویدیو"),
            Trade("motion_graphics", "موشن گرافیک"),
            Trade("animation_studio", "انیمیشن"),
            Trade("social_media_content", "تولید محتوای شبکه اجتماعی"),
        ),
    ),
    TradeGroup(
        "marketing_business",
        "بازاریابی و کسب‌وکار",
        (
            Trade("business_consulting", "مشاوره کسب‌وکار"),
            Trade("management_consulting", "مشاوره مدیریت"),
            Trade("marketing_services", "بازاریابی"),
            Trade("digital_marketing", "دیجیتال مارکتینگ"),
            Trade("social_media_management", "مدیریت شبکه اجتماعی"),
            Trade("market_research", "تحقیقات بازار"),
            Trade("sales_services", "فروش و بازاریابی"),
            Trade("call_center", "مرکز تماس"),
            Trade("customer_support_outsourcing", "خدمات مشتریان برون‌سپاری"),
            Trade("hr_services", "منابع انسانی"),
            Trade("recruitment_agency", "کاریابی"),
        ),
    ),
    TradeGroup(
        "technical_repair",
        "خدمات فنی",
        (
            Trade("technical_services", "خدمات فنی و تعمیرات"),
            Trade("general_repair", "تعمیرات عمومی"),
            Trade("tool_repair", "تعمیر ابزار"),
            Trade("industrial_repair", "تعمیر تجهیزات صنعتی"),
            Trade("electrical_repair", "تعمیر تجهیزات برقی"),
            Trade("electronics_repair", "تعمیر تجهیزات الکترونیکی"),
            Trade("board_repair", "تعمیر برد الکترونیکی"),
            Trade("motor_rewinding", "سیم‌پیچی موتور"),
            Trade("pump_repair", "تعمیر پمپ"),
            Trade("generator_repair", "تعمیر ژنراتور"),
        ),
    ),
    TradeGroup(
        "cleaning_services",
        "نظافت و خدمات منزل",
        (
            Trade("service_company", "شرکت خدماتی"),
            Trade("home_cleaning", "نظافت منزل"),
            Trade("office_cleaning", "نظافت شرکت"),
            Trade("industrial_cleaning", "نظافت صنعتی"),
            Trade("carpet_cleaning", "قالیشویی"),
            Trade("sofa_cleaning", "مبل‌شویی"),
            Trade("laundry", "خشکشویی"),
            Trade("laundry_service", "لباسشویی"),
            Trade("ironing_service", "اتوشویی"),
            Trade("facade_cleaning", "نظافت نمای ساختمان"),
            Trade("pest_control", "سمپاشی ساختمان"),
            Trade("garden_maintenance", "خدمات باغبانی"),
        ),
    ),
    TradeGroup(
        "personal_services",
        "خدمات شخصی",
        (
            Trade("tailoring_services", "خدمات خیاطی"),
            Trade("clothing_repair", "تعمیر پوشاک"),
            Trade("shoe_repair", "تعمیر کفش"),
            Trade("locksmith", "کلیدسازی"),
            Trade("key_copying", "خدمات کپی کلید"),
            Trade("personal_packaging", "خدمات بسته‌بندی شخصی"),
            Trade("home_moving", "خدمات جابه‌جایی منزل"),
        ),
    ),
    TradeGroup(
        "equipment_rental",
        "اجاره تجهیزات",
        (
            Trade("tool_rental", "اجاره ابزار"),
            Trade("industrial_equipment_rental", "اجاره تجهیزات صنعتی"),
            Trade("machinery_rental", "اجاره ماشین‌آلات"),
            Trade("construction_equipment_rental", "اجاره تجهیزات ساختمانی"),
            Trade("audio_equipment_rental", "اجاره تجهیزات صوتی"),
            Trade("camera_rental", "اجاره تجهیزات تصویری"),
        ),
    ),
    TradeGroup(
        "other",
        "سایر",
        (
            #: راهِ فرار. هر کسب‌وکاری که خودش را در فهرستِ بالا پیدا نکند این را
            #: می‌زند — و نبودنش یعنی کاربر یا چیزِ غلطی انتخاب می‌کند یا هیچ‌چیز.
            Trade("other", "سایر"),
        ),
    ),
)


#: نگاشتِ کلید → برچسب، یک بار ساخته می‌شود.
TRADE_LABELS: dict[str, str] = {
    t.key: t.label for g in TRADE_GROUPS for t in g.trades
}

#: کلیدِ گروهِ هر صنف — برای «کلِ این گروه» و گزارش.
TRADE_GROUP_OF: dict[str, str] = {
    t.key: g.key for g in TRADE_GROUPS for t in g.trades
}


def is_valid_trade(key: str) -> bool:
    return key in TRADE_LABELS


def trade_label(key: str | None) -> str:
    """برچسبِ فارسی. کلیدِ ناشناخته خودش برمی‌گردد تا داده‌ی قدیمی گم نشود."""
    if not key:
        return ""
    return TRADE_LABELS.get(key, key)


def trades_of_group(group_key: str) -> tuple[str, ...]:
    for g in TRADE_GROUPS:
        if g.key == group_key:
            return tuple(t.key for t in g.trades)
    return ()


def clean_trades(keys: list[str] | None) -> list[str]:
    """فهرستِ اصنافِ ورودی را یکتا و مرتب می‌کند و ناشناخته‌ها را دور می‌ریزد.

    ترتیبِ خروجی همان ترتیبِ `TRADE_GROUPS` است، نه ترتیبِ ورودی — تا دو ذخیره‌ی
    یکسان دو مقدارِ متفاوت در دیتابیس نسازند.
    """
    if not keys:
        return []
    wanted = set(keys)
    return [t.key for g in TRADE_GROUPS for t in g.trades if t.key in wanted]
